#!/bin/sh

# This script runs the QC process using PLINK on the merged file generated by 00_merge_files.sh

# Requirements: 
# Please refer to readme.md for more information about the requirements

# How to Run:
# Run this script using: sh 03_plink_qc.sh on the command line

# Outputs: 
# - WGS_qc_pass.snplist
# - WGS_qc_pass.log
# - WGS_qc_pass.id

#set output directory (also location of merged files)
data_file_dir="/Data/Input_regenie"

run_plink_qc="plink2 --bfile ukb_allChrs\
 --autosome\
 --maf 0.01 --mac 20 --geno 0.1 --hwe 1e-15 \
 --mind 0.1 --write-snplist --write-samples --remove-nosex\
 --no-id-header --out WGS_qc_pass"

dx run swiss-army-knife -iin="${data_file_dir}/ukb_allChrs.bed" \
   -iin="${data_file_dir}/ukb_allChrs.bim" \
   -iin="${data_file_dir}/ukb_allChrs.fam"\
   -icmd="${run_plink_qc}" --tag="Step1_QC" --instance-type "mem1_ssd1_v2_x16"\
   --destination="${data_file_dir}" --brief --yes
